### ISSUE TITLE
Not recognising CommandInputArraySchema

### ISSUE THREAD

**Issue by illusional** [rabix/benten#45]
Hi, just started using Benten and it's awesome! Just noticed a few small things I'm no sure if my CWL is actually valid or Benten isn't recognising something properly.

I have a Workflow Input of type, but I've got a yellow squiggle under `items` (_Unknown field: items for type InputRecordSchema_) and red under `array` (_Expecting one of: {'record'}_):

```cwl
  fastq:
    id: fastq
    type:
      items: File
      type: array
```

Using that latest development per: `pipx install --spec git+https://github.com/rabix/benten.git@develop benten`

> Also, this line on the README is missing the second hyphen before spec (`--`)

**Comment by kaushik-work** [comment]
@illusional thanks for trying it out and for reporting this bug. 

I have to learn how to infer this from the spec. The relevant part of the spec declares that an `InputParameter` (here `fastq`) is a record whose `type` field can be one of

```
                    "null",
                    "CWLType",
                    "InputRecordSchema",
                    "InputEnumSchema",
                    "InputArraySchema",
                    "string"
```

or an array of the same.

Now, the current code tries to match the record

```
      items: File
      type: array
```
and this should match `InputRecordSchema` or perhaps `InputArraySchema` but fails either because `RecordSchema` and `InputSchema` are missing from the `schema-v1.0.json` file or because I don't understand something about how types are declared in the CWL document.

(Sorry, this are more notes for me for how to fix the issue)

**Comment by kaushik-work** [comment]
Possibly related to common-workflow-language/schema_salad#278

**Comment by kaushik-work** [comment]
Our type matching is too primitive - currently we only match on the field names (whether we satisfy all required fields). This works for most cases, but not in this. We need to add an additional layer where we check if the types of the fields are also satisfied.

The refined algorithm should work in all the following cases 
1. There is only one valid type, but our document does not satisfy that type
2. There are multiple types, and our document partially matches two or more of them.

In case 2 we should return the first partial match. In a later incarnation we should probably develop a "goodness of fit" metric and pick the best matching type.

**Comment by kaushik-work** [comment]
Rather than implement the recursive inference algorithm, I implemented a slight modification to the existing algorithm to

1. Check if record has extra fields (not just missing fields)
2. Consider Maybes during type inference
